const $=s=>document.querySelector(s);const state={videos:[],query:'',oldest:false,scrollY:0,current:null};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function driveId(v){const value=v?.drive_file_id||v?.gdrive_file_id||v?.artifactRunUrl||v?.gdrive_url||v?.drive_url||'';return String(value).match(/(?:file\/d\/|[?&]id=|\/d\/)([\w-]+)/)?.[1]||null}
function driveStreamUrl(v){if(v?.stream_url)return v.stream_url;if(v?.videoUrl)return v.videoUrl;const id=driveId(v);return id?`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`:null}
const formatDate=v=>v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
const formatDuration=v=>Number.isFinite(+v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'';
function filtered(){const q=state.query.toLowerCase();return state.videos.filter(v=>`${v.title||''} ${v.uploader||''}`.toLowerCase().includes(q)).sort((a,b)=>{const d=new Date(a.archivedAt||0)-new Date(b.archivedAt||0);return state.oldest?d:-d})}
function render(){const items=filtered();$('#count').textContent=state.videos.length;$('#result-label').textContent=state.query?`${items.length} result${items.length===1?'':'s'}`:'All videos';$('#sort').innerHTML=`${state.oldest?'Oldest':'Newest'} <span>↕</span>`;$('#clear-search').style.display=state.query?'block':'none';$('#video-list').innerHTML=items.length?items.map(v=>`<article class="video-card" data-id="${esc(v.id||v.sourceUrl)}" tabindex="0"><div class="thumb-wrap">${v.thumbnail?`<img class="thumb" loading="lazy" src="${esc(v.thumbnail)}" alt="">`:''}${formatDuration(v.duration)?`<span class="duration">${formatDuration(v.duration)}</span>`:''}</div><div class="card-copy"><div class="card-title">${esc(v.title||'Untitled video')}</div><div class="card-meta">${esc(v.uploader||'Unknown uploader')}</div><div class="card-date">${formatDate(v.archivedAt)}</div></div></article>`).join(''):'<div class="empty">No videos match that search.</div>';document.querySelectorAll('.video-card').forEach(card=>{const open=()=>openPlayer(state.videos.find(v=>(v.id||v.sourceUrl)===card.dataset.id));card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')open()})})}
function openPlayer(v){if(!v)return;state.current=v;state.scrollY=scrollY;$('#feed-view').hidden=true;$('#player-view').hidden=false;document.body.style.overflow='hidden';$('#player-title').textContent=v.title||'Now playing';$('#meta-title').textContent=v.title||'Untitled video';$('#meta-uploader').textContent=v.uploader||'Unknown uploader';$('#meta-date').textContent=formatDate(v.archivedAt);const id=driveId(v),stream=driveStreamUrl(v);$('#player-mount').replaceChildren();if(stream){const video=document.createElement('video');video.id='video-element';video.className='native-player';video.controls=true;video.playsInline=true;video.preload='metadata';if(v.thumbnail)video.poster=v.thumbnail;video.src=stream;$('#player-mount').append(video)}else{$('#player-mount').innerHTML='<div class="empty">No playable file is attached to this record.</div>'}const fallback=$('#iframe-fallback');fallback.hidden=!id;fallback.onclick=()=>{$('#player-mount').innerHTML=`<iframe src="https://drive.google.com/file/d/${encodeURIComponent(id)}/preview" allow="autoplay; fullscreen" allowfullscreen title="${esc(v.title||'Video preview')}"></iframe>`;fallback.hidden=true};const y=$('#youtube-link');y.href=v.sourceUrl||'#';y.textContent=/dailymotion\.com|dai\.ly/i.test(v.sourceUrl||'')?'Dailymotion ↗':'YouTube ↗';y.style.display=v.sourceUrl?'inline-flex':'none';const d=$('#drive-link');d.href=id?`https://drive.google.com/file/d/${encodeURIComponent(id)}/view`:'#';d.style.display=id?'inline-flex':'none';$('#player-view').querySelector('.player-scroll').scrollTop=0}
function closePlayer(){$('#player-mount').replaceChildren();$('#player-view').hidden=true;$('#feed-view').hidden=false;document.body.style.overflow='';requestAnimationFrame(()=>scrollTo(0,state.scrollY))}
fetch('data/videos.json',{cache:'no-store'}).then(r=>r.json()).then(v=>{state.videos=Array.isArray(v)?v:[];render()}).catch(()=>{$('#video-list').innerHTML='<div class="empty">Archive metadata unavailable.</div>'});$('#search').addEventListener('input',e=>{state.query=e.target.value.trim();render()});$('#clear-search').addEventListener('click',()=>{$('#search').value='';state.query='';render();$('#search').focus()});$('#sort').addEventListener('click',()=>{state.oldest=!state.oldest;render()});$('#back').addEventListener('click',closePlayer);addEventListener('keydown',e=>e.key==='Escape'&&!$('#player-view').hidden&&closePlayer());let sy=0;$('#player-view').addEventListener('touchstart',e=>{sy=e.touches[0].clientY},{passive:true});$('#player-view').addEventListener('touchend',e=>{if(e.changedTouches[0].clientY-sy>90)closePlayer()},{passive:true});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));